<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.7.0
 * @copyright Copyright (c) 2019, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Centoswebpanel.name'] = "WebPanel do CentOS";
$lang['Centoswebpanel.module_row'] = "Servidor";
$lang['Centoswebpanel.module_row_plural'] = "Servidores";
$lang['Centoswebpanel.module_group'] = "Grupo de Servidores";
$lang['Centoswebpanel.tab_firewall'] = "Firewall";
$lang['Centoswebpanel.tab_client_firewall'] = "Firewall";
$lang['Centoswebpanel.add_module_row'] = "Adicionar servidor


";
$lang['Centoswebpanel.add_module_group'] = "Adicionar grupo de servidores";
$lang['Centoswebpanel.manage.module_rows_title'] = "Servidores";
$lang['Centoswebpanel.manage.module_groups_title'] = "Grupos de Servidores";
$lang['Centoswebpanel.manage.module_rows_heading.name'] = "Rótulo do Servidor";
$lang['Centoswebpanel.manage.module_rows_heading.hostname'] = "nome de anfitrião";
$lang['Centoswebpanel.manage.module_rows_heading.accounts'] = "Contas";
$lang['Centoswebpanel.manage.module_rows_heading.options'] = "Opções";
$lang['Centoswebpanel.manage.module_groups_heading.name'] = "nome do grupo";
$lang['Centoswebpanel.manage.module_groups_heading.servers'] = "Contagem de Servidores";
$lang['Centoswebpanel.manage.module_groups_heading.options'] = "Opções";
$lang['Centoswebpanel.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Centoswebpanel.manage.module_rows.edit'] = "Editar";
$lang['Centoswebpanel.manage.module_groups.edit'] = "Editar";
$lang['Centoswebpanel.manage.module_rows.delete'] = "Excluir";
$lang['Centoswebpanel.manage.module_groups.delete'] = "Apagar";
$lang['Centoswebpanel.manage.module_rows.confirm_delete'] = "Tem certeza de que deseja excluir este servidor?";
$lang['Centoswebpanel.manage.module_groups.confirm_delete'] = "Tem certeza de que deseja excluir este grupo de servidores?";
$lang['Centoswebpanel.manage.module_rows_no_results'] = "Não há servidores.";
$lang['Centoswebpanel.manage.module_groups_no_results'] = "Não há grupos de servidores.";
$lang['Centoswebpanel.order_options.first'] = "Primeiro servidor não completo";
$lang['Centoswebpanel.order_options.roundrobin'] = "Distribuir uniformemente entre servidores";
$lang['Centoswebpanel.add_row.box_title'] = "Adicionar servidor do WebPanel do CentOS


";
$lang['Centoswebpanel.add_row.basic_title'] = "Configurações básicas


";
$lang['Centoswebpanel.add_row.name_servers_title'] = "Servidores de nomes


";
$lang['Centoswebpanel.add_row.notes_title'] = "Notas


";
$lang['Centoswebpanel.add_row.name_server_btn'] = "Adicionar servidor de nomes adicional


";
$lang['Centoswebpanel.add_row.name_server_col'] = "Nome do servidor


";
$lang['Centoswebpanel.add_row.name_server_host_col'] = "Hostname";
$lang['Centoswebpanel.add_row.name_server'] = "Servidor de nomes %1\$s


"; // %1$s is the name server number (e.g. 3)
$lang['Centoswebpanel.add_row.remove_name_server'] = "remover";
$lang['Centoswebpanel.add_row.add_btn'] = "Adicionar servidor";
$lang['Centoswebpanel.edit_row.box_title'] = "Edite o servidor do WebPanel do CentOS


";
$lang['Centoswebpanel.edit_row.basic_title'] = "Configurações básicas


";
$lang['Centoswebpanel.edit_row.name_servers_title'] = "Servidores de nomes";
$lang['Centoswebpanel.edit_row.notes_title'] = "notas";
$lang['Centoswebpanel.edit_row.name_server_btn'] = "Adicionar servidor de nomes adicional


";
$lang['Centoswebpanel.edit_row.name_server_col'] = "Nome do servidor";
$lang['Centoswebpanel.edit_row.name_server_host_col'] = "Hostname";
$lang['Centoswebpanel.edit_row.name_server'] = "Servidor de nomes %1\$s


"; // %1$s is the name server number (e.g. 3)
$lang['Centoswebpanel.edit_row.remove_name_server'] = "Remover";
$lang['Centoswebpanel.edit_row.add_btn'] = "Editar servidor";
$lang['Centoswebpanel.row_meta.server_name'] = "Rótulo do Servidor";
$lang['Centoswebpanel.row_meta.host_name'] = "nome de anfitrião";
$lang['Centoswebpanel.row_meta.api_key'] = "Chave API";
$lang['Centoswebpanel.row_meta.use_ssl'] = "Use SSL ao se conectar à API (recomendado)";
$lang['Centoswebpanel.row_meta.account_limit'] = "Limite de conta";
$lang['Centoswebpanel.package_fields.package'] = "ID do pacote";
$lang['Centoswebpanel.package_fields.inode'] = "Inodes Máximos";
$lang['Centoswebpanel.package_fields.nofile'] = "Arquivos Máximos";
$lang['Centoswebpanel.package_fields.nproc'] = "Processo Máximo";
$lang['Centoswebpanel.service_field.domain'] = "Domínio ";
$lang['Centoswebpanel.service_field.username'] = "Nome do usuário";
$lang['Centoswebpanel.service_field.password'] = "Palavra-chave";
$lang['Centoswebpanel.tab_firewall.unblock_ip_title'] = "Desbloquear IP";
$lang['Centoswebpanel.tab_firewall.field_ip_address'] = "Endereço de IP";
$lang['Centoswebpanel.tab_firewall.button_unblock'] = "Desbloquear";
$lang['Centoswebpanel.tab_client_firewall.unblock_ip_title'] = "Desbloquear IP";
$lang['Centoswebpanel.tab_client_firewall.field_ip_address'] = "Endereço de IP";
$lang['Centoswebpanel.tab_client_firewall.button_unblock'] = "Desbloquear";
$lang['Centoswebpanel.service_info.username'] = "Nome";
$lang['Centoswebpanel.service_info.password'] = "Palavra-chave";
$lang['Centoswebpanel.service_info.server'] = "Servidor";
$lang['Centoswebpanel.service_info.options'] = "Opções";
$lang['Centoswebpanel.service_info.option_login'] = "Entrar";
$lang['Centoswebpanel.service_field.tooltip.username'] = "Você pode deixar o nome de usuário em branco para gerar automaticamente um.";
$lang['Centoswebpanel.service_field.tooltip.password'] = "Você pode deixar uma senha em branco para gerar automaticamente uma.";
$lang['Centoswebpanel.!error.server_name_valid'] = "Você deve inserir um rótulo de servidor.";
$lang['Centoswebpanel.!error.host_name_valid'] = "O nome do host parece ser inválido.


";
$lang['Centoswebpanel.!error.user_name_valid'] = "O nome do usuário parece ser inválido.";
$lang['Centoswebpanel.!error.remote_api_key_valid'] = "A chave da API parece ser inválida.";
$lang['Centoswebpanel.!error.remote_api_key_valid_connection'] = "Uma conexão com o servidor não pôde ser estabelecida. Por favor, verifique se o nome do host e a chave da API estão corretos.";
$lang['Centoswebpanel.!error.account_limit_valid'] = "O limite de conta deve ser deixado em branco (para contas ilimitadas) ou definido para algum valor inteiro.";
$lang['Centoswebpanel.!error.name_servers_valid'] = "Um ou mais dos servidores de nomes inseridos são inválidos.";
$lang['Centoswebpanel.!error.name_servers_count'] = "Você deve definir pelo menos dois servidores de nomes";
$lang['Centoswebpanel.!error.meta[package].empty'] = "Um pacote do CentOS WebPanel é necessário";
$lang['Centoswebpanel.!error.meta[inode].valid'] = "O máximo Inodes deve ser um valor numérico.


";
$lang['Centoswebpanel.!error.meta[nofile].valid'] = "O máximo de arquivos deve ser um valor numérico.";
$lang['Centoswebpanel.!error.meta[nproc].valid'] = "O processo máximo deve ser um valor numérico.


";
$lang['Centoswebpanel.!error.api.internal'] = "Ocorreu um erro interno ou o servidor não respondeu ao pedido.


";
$lang['Centoswebpanel.!error.module_row.missing'] = "Ocorreu um erro interno. A linha do módulo está indisponível.";
$lang['Centoswebpanel.!error.centoswebpanel_domain.format'] = "Por favor, insira um nome de domínio válido, por exemplo domain.com.


";
$lang['Centoswebpanel.!error.centoswebpanel_domain.test'] = "O nome do domínio não pode começar com 'teste'.


";
$lang['Centoswebpanel.!error.centoswebpanel_username.format'] = "O nome de usuário pode conter apenas letras e números e pode não começar com um número.";
$lang['Centoswebpanel.!error.centoswebpanel_username.test'] = "O nome de usuário pode não começar com 'teste'.


";
$lang['Centoswebpanel.!error.centoswebpanel_username.length'] = "O nome de usuário deve ter entre 1 e 16 caracteres de comprimento.


";
$lang['Centoswebpanel.!error.centoswebpanel_password.valid'] = "A senha deve ter pelo menos 8 caracteres de comprimento.


";
$lang['Centoswebpanel.!error.centoswebpanel_password.matches'] = "Senha e Confirmação de Senha não coincidem.";
?>